### ISSUE TITLE
Getting "This extension is not installable on any currently installed products" despite having ssms 2016 installed...

### ISSUE THREAD

**Issue by TaoK** [SQL-MisterMagoo/SSMSX#1]
### Installed product versions
- Visual Studio: community 2013: 12.0.31101.00 Update 4
- SSMS: 2016: 13.0.15500.91
- This extension: just downloaded off the CI page (install log says 1.1.6)

### Description
I try to install the extension by double-clicking on the SSMSX v1.1.6.vsix file, but the vsix installer says  "This extension is not installable on any currently installed products".

Looking up the details in the log, linked at the bottom of the pop-up, I see:

```
11/18/2016 01:00:37 - 	InstalledByMSI  : False
11/18/2016 01:00:37 - 	SupportedFrameworkVersionRange : [4.5,)
11/18/2016 01:00:37 - 
11/18/2016 01:00:37 - 	Supported Products : 
11/18/2016 01:00:37 - 		ssms
11/18/2016 01:00:37 - 			Version : [13.0]
11/18/2016 01:00:37 - 
11/18/2016 01:00:37 - 	References      : 
11/18/2016 01:00:37 - 
11/18/2016 01:00:37 - Searching for applicable products...
11/18/2016 01:00:37 - Found installed product - Microsoft Visual Studio Community 2013
11/18/2016 01:00:37 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
11/18/2016 01:00:37 - Found installed product - Global Location
11/18/2016 01:00:37 - Found installed product - ssms
11/18/2016 01:00:37 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

### Steps to recreate
1. Download the installer
2. Double-click on it

### Current behavior
It is giving me the error noted above.

### Expected behavior
It should be offering ssms 2016 as an installation target, and asking me to confirm I want to install this extension for this software.

**Comment by TaoK** [comment]
(full disclosure: I only started looking at this because I was trying to do exactly the same, use vsix to add my extension (https://github.com/TaoK/PoorMansTSqlFormatter) to ssms 2016, and I couldn't get it to work. I stumbled across this project, saw the code, thought "but that's the same thing I'm doing, why does it work for them??", and then found that... it doesn't work. At least on my machine.

**Comment by SQL-MisterMagoo** [comment]
Update your SSMS, there were issues with the earlier builds.

**Comment by TaoK** [comment]
Yep, just updated to SSMS 16.5, version number 13.0.16000.28 - no joy, no change in behavior. From everything that I read online, this is perfectly expected - the vsix installer will not install stuff into SSMS, even 2016.
As far as I can tell from reading around, the way all the SSMS extension developers have been making this work is by:
1. Preparing an installer to pop the unpacked vsix package files into the right place (a new folder in "C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Extensions") AND add a registry entry somewhere to tell SSMS to "SkipLoading" the package
2. Implementing a funky event handler to set some registry key to repeatedly set this "SkipLoading" registry entry, every time SSMS is exiting (because SSMS will reset it to 0 after successfully loading, and if it is absent or 0 SSMS will try to load the package at the wrong time and fail - or something like that).

The only semi-sane description of the process that I have found is at: http://www.sqlservercentral.com/Forums/Topic1802009-3740-1.aspx

(but I haven't had any time to play with it, so dunno if it actually works for me...)

Does the vsix installer work for you?? You double-click on the "SSMSX v1.1.6.vsix" file and it offers to install in SSMS?

**Comment by SQL-MisterMagoo** [comment]
Hi, Yes, I can double click the VSIX and install the extension.
![2016-11-18 13_46_02-vsix installer](https://cloud.githubusercontent.com/assets/11338430/20432174/dc3f5b62-ad95-11e6-9023-1789043796cd.png)

The problem with VSIX not recognising SSMS was fixed after I submitted this connect item [https://connect.microsoft.com/SQLServer/Feedback/Details/2602339](https://connect.microsoft.com/SQLServer/Feedback/Details/2602339) but I guess there is a chance that your previous install has left some mess behind in the registry - details of where to look in the connect item.

There is still a problem with Packages not working in SSMS, for which you can apply to the MS dev team in charge for a "Whitelisted" package GUID - I haven't done that because I am just using MEF editor extensions, which don't use packages.

Thanks for pointing out that SqlServerCentral post as I am the original source of the SkipLoading workaround and didn't know it was being passed off as someone else's work :smile:

Leigh

**Comment by BognarPal** [comment]
I installed the VS 2017 RC1. This is using vsixinstaller.exe version 15.0.25920. 
When I tried double click the VSIX i got the same error message (VSIXInstaller.NoApplicableSKUsException).

With older version of vsixinstaller (14.0.25240.1) is working

**Comment by SQL-MisterMagoo** [comment]
@BognarPal The initial release did not include support for installing against that version of SSMS.

I have added it now.

**Comment by ErikEJ** [comment]
@SQL-MisterMagoo VS 2017 RC1 is not the same a SSMS 2017 RC1 ! (You have enabled support for that in this change, bit @BognarPal  mentions VS 2017 (which I assume this extension does not support at all)

**Comment by SQL-MisterMagoo** [comment]
Ah yes, my mistake. Absolutely, this is not intended for VS, but is for SSMS only.
